on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  validate_docs:
    name: Validate CLI Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: go.mod

      - name: Build CLI docs
        run: make docs

      - name: Detect Uncommitted Docs
        id: validate_docs
        run: make docs-check

      - uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2.9.4
        if: always() && (steps.validate_docs.outcome == 'failure')
        with:
          header: pr-docs-error
          message: |
            Uncommitted changes were detected in the `docs/` directory.  Please run `make docs` and commit the changes to your branch.

      # Delete a previous comment when the docs have been updated
      - if: ${{ steps.validate_docs.outcome == 'success' }}
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2.9.4
        with:
          header: pr-docs-error
          delete: true